### ISSUE TITLE
Example 14 customized toolbar is missing? 

### ISSUE THREAD

**Issue by bh-adrienne** [PSPDFKit/pspdfkit-web-examples-catalog#1]
The link from here: https://web-examples.pspdfkit.com/customized-toolbar

doesn't seem to exist, though the demo does work

**Comment by philipp-spiess** [comment]
Hey @bh-adrienne!

Huh we forgot to publish this example, thank you for reminding us. It's up now! https://github.com/PSPDFKit/pspdfkit-web-examples-catalog/tree/master/examples/14-customized-toolbar
