### ISSUE TITLE
Version: 2019.1.2

### ISSUE THREAD

**Issue by MelStern** [PSPDFKit/pspdfkit-web-examples-catalog#2]
Hello,

when I clone your git repo I only get the version: 2019.1.2 but in your showcase the current version is: 2019.3.0. How can I update? The Peek Annotation doesn't work correctly in version 2019.1.2. 

Thanks Melanie

**Comment by philipp-spiess** [comment]
Hey Melanie,

I assume you use docker-compose to run the catalog. This will start PSPDFKit Server in a Docker container. It could be that you have run the script some time ago that it picked up 2019.1.2 already. To update, you just need to upgrade the docker container with these command:

```
docker-compose down
docker pull docker.pspdfkit.com/pspdfkit 
docker-compose up
```

This should do the trick! Let me know if it works. 🙂

**Comment by MelStern** [comment]
Thank you Philipp, everything worked out wonderfully. I am now on the newest version.

**Comment by philipp-spiess** [comment]
Happy to hear that! Feel free to reach out to us via https://pspdfkit.com/support/request/ if you have any other questions.
