### ISSUE TITLE
A few examples from https://web-examples.pspdfkit.com/ are missing

### ISSUE THREAD

**Issue by grund3g** [PSPDFKit/pspdfkit-web-examples-catalog#5]
Hi,

It looks like some examples are missing:
- [https://github.com/PSPDFKit/pspdfkit-web-examples-catalog/tree/master/examples/23-presentation-mode](https://github.com/PSPDFKit/pspdfkit-web-examples-catalog/tree/master/examples/23-presentation-mode)
- [https://github.com/PSPDFKit/pspdfkit-web-examples-catalog/tree/master/examples/24-form-designer](https://github.com/PSPDFKit/pspdfkit-web-examples-catalog/tree/master/examples/24-form-designer)
- [https://github.com/PSPDFKit/pspdfkit-web-examples-catalog/tree/master/examples/25-annotations-inspector]( https://github.com/PSPDFKit/pspdfkit-web-examples-catalog/tree/master/examples/25-annotations-inspector)

**Comment by miguelcalderon** [comment]
Thank you for reporting this, and sorry for the delay in the answer!

Our public demo is not automatically synced with this repo, so sometimes it may take a while for new examples to make it there (they are published now).
